spring:
  mail: # 邮箱信息配置
    host: smtp.163.com
    username: m15201373116@163.com
    password: wang521 # 邮箱配置个人的
  datasource: # 数据源配置
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/skywalking?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  data: # es配置
    elasticsearch:
      cluster-name: local-es
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true


# 告警邮箱配置
alarm:
  mail:
    from: m15201373116@163.com
    to: m15201373116@163.com
    subject: 服务告警





