spring:
  cloud:
    stream:
      binders:
        default-mq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 10.4.82.62
                port: 5672
                username: roberto
                password: roberto
                virtual-host: /qijia.wang
      bindings:
        myInPut:
          destination: spring.cloud.stream.test.direct
          group: cloud.stream.send
      rabbit:
        bindings:
          myInPut:
            consumer:
              exchangeType: direct
              acknowledge-mode: manual
              bindingRoutingKey: cloud.stream.send
              queueNameGroupOnly: true
